import json
import os

def merge_i18n():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    json_path = os.path.join(base_dir, 'js', 'i18n_data.json')
    js_path = os.path.join(base_dir, 'js', 'i18n.js')

    print(f"Reading JSON from {json_path}")
    with open(json_path, 'r', encoding='utf-8') as f:
        new_data = f.read() # Read as raw string to inject directly

    # Create the injection code
    # We use the raw JSON string to avoid python formatting issues
    injection_code = f"""

// --- Auto-Appended Migration Data (Generated by tools/merge_i18n.py) ---
(function() {{
    const extraData = {new_data};
    
    if (window.I18N) {{
        // Merge ZH
        if (window.I18N.zh && extraData.zh) {{
            Object.assign(window.I18N.zh, extraData.zh);
        }}
        // Merge EN
        if (window.I18N.en && extraData.en) {{
            Object.assign(window.I18N.en, extraData.en);
        }}
        
        // Optional: Ensure other languages also get English fallbacks if needed
        // But for now we just merge what we have.
        console.log("I18N Data Merged Successfully");
    }}
}})();
"""

    print(f"Appending to {js_path}")
    with open(js_path, 'a', encoding='utf-8') as f:
        f.write(injection_code)
    
    print("Done.")

if __name__ == '__main__':
    merge_i18n()
